Numpy - Numerical Python

Advantages of Numpy Arrays:

1. Allow several Mathematical Operation
2. Faster Operations

In [2]:
import numpy as np


# List Vs Numpy - Time Taken

In [3]:
from time import process_time


TIme Taken by a List

In [4]:
python_list = [i for i in range(100000000)] # Inset values to list from 0 to 10000

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)


6.828125


In [5]:
np_array = np.array([i for i in range(100000000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)


0.0625


Numpy is Faster

# Numpy Arrays

In [6]:
# List
list1 = [1,2,3,5,6]
print(list1)
type(list1)

[1, 2, 3, 5, 6]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# Creating a ID Array

a = np.array([1,2,4,5])
print(a)

[1 2 4 5]


In [9]:
a.shape

(4,)

In [11]:
# Create a 2D Array

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)], dtype=float)
print(c)


[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


# Initial Placeholders in Numpy Array

Inital values prenset in the Numpy Array

In [17]:
# create a numpy array of Zero

x = np.zeros((4,5))
print(x)
type(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


numpy.ndarray

In [18]:
# Create a numpy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Array of a particular value

z = np.full((5,4), 5)

print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
# Create an identity matrix

a = np.eye((5))
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create a numpy array with random values

b = np.random.random((3,4))
b = np. random.randint((3,4))
print(b)

[[0.39086588 0.6861362  0.70122215 0.31651904]
 [0.02472887 0.25622714 0.84027662 0.26656999]
 [0.28186798 0.72977132 0.42468793 0.68274466]]


In [27]:
c = np. random.randint(10,100,(3,4))
print(c)

[[68 17 78 27]
 [36 66 55 10]
 [43 71 37 40]]


In [35]:
# Create array of evenly spaced values -> specifying the number of values required

d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [33]:
# Array of evenly spaced values -> specifying the step

e = np.arange(10,30,3)
print(e)

[10 13 16 19 22 25 28]


In [36]:
# Convert a list to an numpy array

list2 = [10,11,12,14,15]
print(type(list2))
np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

<class 'list'>
[10 11 12 14 15]
<class 'numpy.ndarray'>


# Analysing a Numpy Array

In [37]:
c = np.random.randint(20,100, (6,6))
print(c)

[[81 23 67 58 94 25]
 [48 62 30 77 89 51]
 [65 72 93 81 25 20]
 [39 79 98 45 84 73]
 [76 96 96 39 26 65]
 [51 80 79 41 23 60]]


In [38]:
# Array dimension
print(c.shape)

(6, 6)


In [39]:
# Number of dimensions
print(c.ndim)

2


In [40]:
# Number of elements present in an array

print(c.size)

36


In [41]:
# Checking the data types of values in the array

print(c.dtype)

int32


# Mathematical Operator on Numpy Array

In [42]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
x = np.array((1,2,3,4,5))
y = np.array((6,7,8,9,10))

print(x + y)

[ 7  9 11 13 15]


In [45]:
a = np.random.randint(10,30,(3,3))
b = np.random.randint(20,40, (3,3))
print(a)
print(b)

[[13 26 20]
 [24 25 20]
 [26 18 24]]
[[30 27 36]
 [34 30 20]
 [26 29 21]]


In [46]:
print(a + b)

[[43 53 56]
 [58 55 40]
 [52 47 45]]


In [47]:
print(a - b)

[[-17  -1 -16]
 [-10  -5   0]
 [  0 -11   3]]


In [48]:
print(a * b)

[[390 702 720]
 [816 750 400]
 [676 522 504]]


In [49]:
print(a / b)

[[0.43333333 0.96296296 0.55555556]
 [0.70588235 0.83333333 1.        ]
 [1.         0.62068966 1.14285714]]


In [50]:
print(a % b)

[[13 26 20]
 [24 25  0]
 [ 0 18  3]]


In [51]:
print( a ** b)

[[ 1891174425 -1476395008           0]
 [          0  1180241297           0]
 [  603979776   536870912           0]]
