# Importing Dependencies

In [3]:
import numpy as np
import pandas as pd

# Create a Matrix Using Numpy

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [6]:
matrix_1.shape

(2, 2)

In [9]:
matrix_2 = np.array([[10,24,45],[21,56,23], [45,67,11]])
print(matrix_2)

[[10 24 45]
 [21 56 23]
 [45 67 11]]


In [10]:
matrix_2.shape

(3, 3)

# Creating Matrices with Random Values

In [11]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.26022554 0.18673308 0.85864864]
 [0.4966948  0.98098735 0.50744372]
 [0.77770012 0.18055293 0.46088446]]


In [16]:
# Creating Matrix with random integers
random_matrix_int = np.random.randint(100, size=(3,3)  )
print(random_matrix_int)

[[ 2 77 78]
 [36 41 38]
 [57 94 63]]
