# Importing Dependencies

In [3]:
import numpy as np
import pandas as pd

# Create a Matrix Using Numpy

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [6]:
matrix_1.shape

(2, 2)

In [9]:
matrix_2 = np.array([[10,24,45],[21,56,23], [45,67,11]])
print(matrix_2)

[[10 24 45]
 [21 56 23]
 [45 67 11]]


In [10]:
matrix_2.shape

(3, 3)

# Creating Matrices with Random Values

In [11]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.26022554 0.18673308 0.85864864]
 [0.4966948  0.98098735 0.50744372]
 [0.77770012 0.18055293 0.46088446]]


In [16]:
# Creating Matrix with random integers
random_matrix_int = np.random.randint(100, size=(3,3)  )
print(random_matrix_int)

[[ 2 77 78]
 [36 41 38]
 [57 94 63]]


# Matrix With all the values 1

In [18]:
matrix_3 = np.ones((3,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# All values integers

matrix_3 = np.ones((3,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Null Matrix or Zero Matrix

In [23]:
null_matrix = np.zeros((3,3))
print(null_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# Null Matrix integers

null_int_matrix = np.zeros((4,4), dtype=int)
print(null_int_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Identity Matrix

In [28]:
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:

identity_matrix = np.eye(6, 6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Transpose of a Matrix

In [32]:
mat_A = np.random.randint(100, size=(3,3))
print(mat_A)

[[27 15 48]
 [40 54 28]
 [82 67 67]]


In [33]:
transpose = np.transpose(mat_A)
print(transpose)

[[27 40 82]
 [15 54 67]
 [48 28 67]]
