Dimensionality Reduction:

1. Feature Selection
2. Feature Extraction - Principal Component Analysis (PCA)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
X, Y = make_blobs(n_samples=500, n_features=5, centers=3, cluster_std=1.5, random_state=42)

In [3]:
print(X)

[[ -9.85712583   9.52196609   6.40680626  -6.81757623  -7.86054541]
 [ -8.04717781   8.40261648   6.40946097  -4.33576029  -6.70289196]
 [ -3.73690895   6.7601386    4.24877609   0.28504117  -7.10318219]
 ...
 [ -5.82805     -7.29173339   7.48633693   2.71623974   7.33823548]
 [ -2.48648271   9.67739715   6.21190845   1.03031506  -7.54637531]
 [ -8.63901448 -10.68852991   8.36601977   4.94211449   3.77070371]]


In [4]:
print(Y)

[2 2 0 1 2 0 0 1 1 0 0 0 1 2 2 2 1 1 0 2 0 1 1 2 0 2 1 1 2 1 1 0 1 2 0 0 1
 1 2 2 0 2 1 2 0 0 2 1 0 0 0 1 0 1 1 1 1 0 1 2 1 2 1 1 1 0 2 2 2 2 1 0 0 2
 1 2 1 2 2 0 0 1 0 0 1 0 0 0 2 0 2 1 0 2 2 2 2 0 2 1 0 1 0 2 1 2 0 2 0 1 1
 2 0 1 0 1 1 1 0 1 2 0 2 2 1 0 2 1 2 0 2 1 2 2 0 0 1 0 0 1 0 0 1 1 0 0 1 2
 2 1 1 1 0 0 0 0 2 2 1 1 0 2 2 0 2 0 0 1 1 1 0 0 1 0 0 1 2 0 0 2 1 1 2 2 0
 0 1 0 0 1 1 2 1 2 1 0 2 2 0 1 1 2 2 2 2 2 2 2 0 2 0 2 0 0 1 1 2 0 1 1 1 0
 0 1 1 0 2 2 2 1 2 1 2 0 1 1 0 1 1 0 0 0 2 0 0 2 2 0 1 1 1 1 0 0 1 0 0 0 1
 0 2 2 1 1 0 2 1 2 1 0 1 1 1 2 0 0 0 2 0 2 0 0 1 0 0 2 2 2 0 1 2 0 2 2 0 0
 2 0 2 2 1 1 2 2 1 1 0 1 0 2 1 0 2 1 0 1 2 2 2 0 0 0 0 1 2 1 2 2 2 0 1 1 2
 1 0 2 2 2 0 1 1 1 2 2 1 2 1 1 2 2 2 2 0 0 2 2 1 2 1 2 0 0 0 1 0 0 2 0 0 2
 2 1 0 2 1 2 1 0 1 0 2 0 1 1 0 1 0 1 0 1 2 1 2 1 2 1 0 0 0 1 1 2 2 0 1 0 0
 1 0 2 1 2 2 2 1 1 1 2 2 2 0 2 1 1 0 0 0 1 2 0 2 2 2 0 0 1 2 1 1 0 1 2 0 1
 1 1 0 2 1 0 1 2 1 1 0 0 1 2 0 1 2 1 1 1 2 0 1 1 2 0 2 2 2 0 2 2 2 2 2 2 1
 1 0 2 2 1 1 0 2 0 0 2 2 