# Importing Required Libraries

In [2]:
import numpy as np
import pandas as pd

# Matrix Addition

Two matrices can be only added if they have same shape

In [27]:
# Creating two matrices

matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])



In [28]:
print(matrix_1)

[[3 5]
 [6 7]]


In [29]:
print(matrix_2)

[[5 7]
 [1 2]]


In [30]:
matrix_1.shape

(2, 2)

In [31]:
matrix_2.shape

(2, 2)

In [32]:
# Adding Two Matrices

sum = matrix_1 + matrix_2

In [33]:
print(sum)

[[ 8 12]
 [ 7  9]]


In [34]:
#   Create two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,3))


In [36]:
print(mat1)

[[87 11 97]
 [67 74 51]
 [88 41 30]]


In [37]:
print(mat2)

[[19 89 81]
 [12 78 32]
 [ 3 41 64]]


In [38]:
sum = np.add(mat1, mat2)

In [39]:
print(sum)

[[106 100 178]
 [ 79 152  83]
 [ 91  82  94]]


In [40]:
#   Create two matrices with random values

mat3= np.random.randint(100, size=(3,3))
mat4 = np.random.randint(100, size=(4,3))

In [41]:
sum_2 = np.sum(mat3, mat4)

TypeError: only integer scalar arrays can be converted to a scalar index

we are getting this error because shape of matrix 3 and matrix 4 are different

# Matrix Subtraction

In [42]:
# Creating two Matrices

matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])


In [43]:
print(matrix_1)

[[3 5]
 [6 7]]


In [44]:
print(matrix_2)

[[5 7]
 [1 2]]


In [45]:
difference = matrix_1 - matrix_2

In [46]:
print(difference)

[[-2 -2]
 [ 5  5]]


In [47]:
# Creating two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,3))

In [48]:
print(mat1)

[[50 51 89]
 [80 62 42]
 [58  9 82]]


In [49]:
print(mat2)

[[44  0 36]
 [44 75 99]
 [98 30 45]]


In [50]:
diff = np.subtract(mat1, mat2)

In [51]:
print(diff)

[[  6  51  53]
 [ 36 -13 -57]
 [-40 -21  37]]


# Multiplying a Matrix by a Scalar

In [52]:
x = 5
y = np.random.randint(10, size=(3,3))


In [53]:
print(y)

[[6 1 4]
 [1 0 8]
 [7 8 9]]


In [54]:
product = np.multiply(x,y)

In [56]:
print(product)

[[30  5 20]
 [ 5  0 40]
 [35 40 45]]


# Multiplying 2 Matrix

In [57]:

#   Create two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,4))


In [58]:
print(mat1)

[[48 17 15]
 [86  1 47]
 [80 64 27]]


In [59]:
print(mat2)

[[96 53 50 51]
 [39 93 65  1]
 [70 81 87  0]]


In [60]:
product = np.dot(mat1,mat2)

In [61]:

print(product)

[[ 6321  5340  4810  2465]
 [11585  8458  8454  4387]
 [12066 12379 10509  4144]]


In [62]:
product.shape

(3, 4)

In [64]:
# If first matrix col and second matrix row should be same then only multiplying two matrices are possible


mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(4,3))


In [65]:
product = np.dot(mat1, mat2)

ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

# Element Wise Matrix Multiplication