# Importing Required Libraries

In [2]:
import numpy as np
import pandas as pd

# Matrix Addition

Two matrices can be only added if they have same shape

In [3]:
matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])

matrix_add = matrix_1 + matrix_2

print(matrix_add)

[[ 8 12]
 [ 7  9]]


In [4]:
matrix_add.shape

(2, 2)

In [14]:
print(np.add(matrix_1, matrix_2))

[[ 8 12]
 [ 7  9]]


In [13]:
#   Create two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,3))
print(mat1+mat2)

[[115  56 142]
 [171 124  76]
 [ 74  24  43]]


# Matrix Subtraction

In [5]:
matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])

matrix_sub = matrix_1 - matrix_2

print(matrix_sub)

[[-2 -2]
 [ 5  5]]


In [6]:
matrix_sub.shape

(2, 2)

In [15]:
print(np.subtract(matrix_1, matrix_2))

[[-2 -2]
 [ 5  5]]


# Matrix Multiplication

In [7]:
matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])

matrix_mult = matrix_1 * matrix_2

print(matrix_mult)

[[15 35]
 [ 6 14]]


In [16]:
print(np.multiply(matrix_1, matrix_2))

[[15 35]
 [ 6 14]]
