# Importing Required Libraries

In [56]:
import numpy as np
import pandas as pd

# Matrix Addition

Two matrices can be only added if they have same shape

In [57]:
# Creating two matrices

matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])



In [58]:
print(matrix_1)

[[3 5]
 [6 7]]


In [59]:
print(matrix_2)

[[5 7]
 [1 2]]


In [60]:
matrix_1.shape

(2, 2)

In [61]:
matrix_2.shape

(2, 2)

In [62]:
# Adding Two Matrices

sum = matrix_1 + matrix_2

In [63]:
print(sum)

[[ 8 12]
 [ 7  9]]


In [64]:
#   Create two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,3))


In [65]:
print(mat1)

[[36 58 24]
 [47 98 60]
 [ 9 18 11]]


In [66]:
print(mat2)

[[54 65 52]
 [98 53  2]
 [67 71  5]]


In [67]:
sum = np.add(mat1, mat2)

In [68]:
print(sum)

[[ 90 123  76]
 [145 151  62]
 [ 76  89  16]]


In [69]:
#   Create two matrices with random values

mat3= np.random.randint(100, size=(3,3))
mat4 = np.random.randint(100, size=(4,3))

In [70]:
sum_2 = np.sum(mat3, mat4)

TypeError: only integer scalar arrays can be converted to a scalar index

we are getting this error because shape of matrix 3 and matrix 4 are different

# Matrix Subtraction

In [ ]:
# Creating two Matrices

matrix_1 = np.array([[3,5], [6,7]])
matrix_2 = np.array([[5,7], [1,2]])


In [ ]:
print(matrix_1)

[[3 5]
 [6 7]]


In [ ]:
print(matrix_2)

[[5 7]
 [1 2]]


In [ ]:
difference = matrix_1 - matrix_2

In [ ]:
print(difference)

[[-2 -2]
 [ 5  5]]


In [ ]:
# Creating two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,3))

In [ ]:
print(mat1)

[[40 36 48]
 [83 87 77]
 [38 17 41]]


In [ ]:
print(mat2)

[[50 52 73]
 [25  9 34]
 [85 55 69]]


In [ ]:
diff = np.subtract(mat1, mat2)

In [ ]:
print(diff)

[[-10 -16 -25]
 [ 58  78  43]
 [-47 -38 -28]]


# Multiplying a Matrix by a Scalar

In [ ]:
x = 5
y = np.random.randint(10, size=(3,3))


In [ ]:
print(y)

[[2 3 3]
 [7 3 5]
 [8 3 0]]


In [ ]:
product = np.multiply(x,y)

In [ ]:
print(product)

[[10 15 15]
 [35 15 25]
 [40 15  0]]


# Multiplying 2 Matrix

In [ ]:

#   Create two matrices with random values

mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(3,4))


In [ ]:
print(mat1)

[[69 34 42]
 [93 91 63]
 [87  0 82]]


In [ ]:
print(mat2)

[[33 52 96 80]
 [42 58  3 20]
 [68 30 54 64]]


In [ ]:
product = np.dot(mat1,mat2)

In [ ]:

print(product)

[[ 6561  6820  8994  8888]
 [11175 12004 12603 13292]
 [ 8447  6984 12780 12208]]


In [ ]:
product.shape

(3, 4)

In [ ]:
# If first matrix col and second matrix row should be same then only multiplying two matrices are possible


mat1= np.random.randint(100, size=(3,3))
mat2 = np.random.randint(100, size=(4,3))


In [ ]:
product = np.dot(mat1, mat2)

ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

# Element Wise Matrix Multiplication

In [71]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [72]:
print(matrix_3)

[[3 0 3]
 [2 4 3]
 [3 4 0]]


In [73]:
print(matrix_4)

[[2 3 4]
 [1 3 0]
 [0 2 1]]


In [74]:
product = np.multiply(matrix_3, matrix_4)

In [75]:
print(product)

[[ 6  0 12]
 [ 2 12  0]
 [ 0  8  0]]


In [76]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [77]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 